### ISSUE TITLE
Consider further optimizations to the attribute protocol

### ISSUE THREAD

**Issue by geeknoid** [istio/old_mixer_repo#111]
There's potential to improve the end-to-end perf for the proxy->mixer attribute-related protocol. Please see the conversation thread for PR #107 for details.

Before attempting these improvements, we need to see what the client-side code in the mixer will look like and have some end-to-end benchmarks with representative traffic.

**Comment by jba** [comment]
As an example, see the use of parallel repeated fields in [pubsub.StreamingPullRequest](https://github.com/googleapis/googleapis/blob/master/google/pubsub/v1/pubsub.proto#L474).

**Comment by geeknoid** [comment]
Good for now.
