### ISSUE TITLE
Support a fallback for time-related expressions

### ISSUE THREAD

**Issue by douglas-reid** [istio/old_mixer_repo#1320]
We should provide a way for specifying a fallback for time expressions.

Possibilities:
- add a `now()` expressions to the IL and AST.
- add code / preprocess adapter for generating a mixer-specific attribute, like `mixer.report.time` or `mixer.received.time`

There are probably other approaches, as well.

**Comment by ZackButcher** [comment]
+1 I hit this pain point in writing stackdriver config and more generally in attempting to test configs. Today you _must_ provide all time attributes when using mixc since we can't provide fallbacks in config, for example.

**Comment by ozevren** [comment]
Having looked at this recently, I'd say now() has some fundamental problems (mostly with cacheability and introducing observability to the ordering of expressions).

I believe the alternatives are request.time and context.time. request.time should be generated in the proxy.

**Comment by ldemailly** [comment]
Issue moved to [istio/istio #4233](https://github.com/istio/istio/issues/4233) via [**ZenHub**](https://www.zenhub.com/)
