### ISSUE TITLE
Support a way for Mixer to mutate a request's headers in flight

### ISSUE THREAD

**Issue by rlguarino** [istio/old_mixer_repo#1333]
Mixer adapters should be capable of producing attributes which are sent back to the proxy and eventually propagated to the Upstream [defined here](https://envoyproxy.github.io/envoy/intro/arch_overview/terminology.html).

**Comment by rlguarino** [comment]
@ZackButcher  I think I remember someone saying that a list of all attributes is sent back to the Envoy filter so it can make caching decisions. Was that just in theory or is that a reality at the moment?

**Comment by ZackButcher** [comment]
[That does happen today](https://github.com/istio/api/blob/master/mixer/v1/check.proto#L105), though attribute values are not sent back.

The work for Mixer to mutate request headers is:
- In Mixer, formalize the concept of "return attributes". Today only `attributes` adapters can produce attributes, and they reside only in Mixer. We need a way for adapters to talk about attributes they inject into the request context, and implementation work to actually support that
- Update the [Mixer API](https://github.com/istio/api/blob/master/mixer/v1/check.proto#L58) to support returning attributes on `Check` responses.
- In [Istio's Envoy HTTP filter](https://github.com/istio/proxy/blob/master/src/envoy/mixer/http_filter.cc) we need support for reading attributes returned by `Check`s and attaching them to the request's header. There's likely some work here in mapping attribute names (`foo.bar.baz`) to HTTP headers (`X-foo-bar-baz` or similar) on top of just pushing the values into the header map.

**Comment by kyessenov** [comment]
This belongs to the general area of "scripting proxy actions". Changing the header is one such action, and can be used to shape the traffic.

**Comment by rlguarino** [comment]
@geeknoid  I don't think that this made it into the 0.3 release. Should this Issue be moved into the istio/istio repository?

**Comment by geeknoid** [comment]
Issue moved to [istio/istio #2706](https://github.com/istio/istio/issues/2706) via [**ZenHub**](https://www.zenhub.com/)
