### ISSUE TITLE
Port Mixer to build using CentOS docker-signed container contents

### ISSUE THREAD

**Issue by sdake** [istio/old_mixer_repo#1347]
Mixer currently builds against debian/ubuntu base images.  This results in some incompatibilities when running on CentOS7.4 kernels as the Xenial kernel and CentOS kernel are not 100% compatible.

Instead permit MIxer to build against a CentOS  target OS.

This is part of a larger port of Istio to CentOS described here: https://github.com/istio/issues/issues/56

**Comment by geeknoid** [comment]
Anything else to do, or can we close this?

**Comment by sdake** [comment]
@geeknoid I've tested master last week on CentOS and it works well.  I don't see any further need to keep this open.  I'm not sure if I originally opened it because of other bugs, or things magically worked themselves out.   We can always reopen a new issue if people run into trouble.
