### ISSUE TITLE
Support Jaeger tracing

### ISSUE THREAD

**Issue by douglas-reid** [istio/old_mixer_repo#1352]
With Envoy supporting Jaeger, it is probably time to update Mixer tracing options to also support Jaeger trace exports.

**Comment by ZackButcher** [comment]
Work to be done:
1. Shift Mixer to read tracing config from the same place as Envoy (today on k8s, a configmap)
    - this will also require some slight logical changes to Zipkin logic inside of `server.go` - we expect a full endpoints: `https://zipkin:9411/v1/api/spans` but the configmap only provides `zipkin:9411`
1. Plumb Jaeger stuff through [server.go](https://github.com/istio/mixer/blob/master/cmd/server/cmd/server.go#L358)
