### ISSUE TITLE
Mixer IL evaluation has slow memory leak.

### ISSUE THREAD

**Issue by ozevren** [istio/old_mixer_repo#1369]
The string table that interns strings in the Mixer IL is slowly accumulating runtime data. This data gets flushed when the expression cache entries get evicted. In case of steady state of no config change and large cache-size, the interned strings will accumulate.

**Comment by ldemailly** [comment]
I'm still not clear exactly which strings end up in that table

can you give an example of the worst case where it would grow unbounded ? (eg if for instance the URI or a cookie would be in that table)

**Comment by mandarjog** [comment]
The string intern table interns *all* strings. For example this includes *values* of all headers, which can be unbounded.

One of the reasons why this is needed is because the IL uses references  from the table instead of direct string refs. This is an intermediate fix.

Other solutions include having two intern tables. One that is request scoped that is auto purged at the end of a request. The other table holds constants that have longer lives.

**Comment by ldemailly** [comment]
@mandarjog I have been trying to get a precise answer to this question 

@ozevren in #1338 was saying "No, not all of it. Only the ones used when evaluation a particular expression that is needed to resolve the request."

which is it :-) ?

**Comment by ozevren** [comment]
As the code stands today, the IL evaluator will not intern strings eagerly.
It will intern them as it encounters them during string evaluation. For
example, if you have this expression: 'request.headers["a"] |
request.header["b"] | "c"', then the initial interned strings will be
"request.headers", "a", "b", and "c". As an example, assume the first
incoming request has "request_headers = {"a": "aval", "b": "bval", "d":
"dval"}". In this case, the expression will short circuit in the first
expression fragment, after evaluating "request.headers["a"]" and "aval"
will be added to the interned strings table, but not the others.

In the future, we'd like to have two lookup tables, one for constants, the
other for per-request interned string table. We should be able to get some
perf gains using this approach and not leak. But this requires some
substantial changes to the request handling path.

In the interim, my initial check-in will avoid a sudden circuit-break and
my follow-up PR (not submitted yet) should reduce the effects of interning
(i.e. over a steady state, the memory consumption should be bounded even in
the presence of open-set inputs).

Does that make sense?

**Comment by kyessenov** [comment]
Have you considered a session context for the evaluator? Assuming Mixer establishes a session for a proxy, the table can be split into both a global inline table (for global constants) and a local inline table, to reuse strings across subsequent Check calls.

**Comment by ldemailly** [comment]
can you just use an LRU ?

**Comment by ozevren** [comment]
My intention, for the short term, is to perturb the code as little as
possible. Adding an LRU or establishing a context/session will touch a
large section of the code. For the longer term, my intention is to make use
of the fact that the API already operates on a string-table model and use
the string table in the API directly, if possible, in the evaluation (thus
avoiding conversions that is causing these problems in the first place).
