### ISSUE TITLE
Incomplete tests: Mixer Expression Language

### ISSUE THREAD

**Issue by hklai** [istio/old_mixer_repo#1389]
Context: [production readiness proposal and plan](https://goo.gl/pmjuYg)

The feature “_Mixer Expression Language_” is identified as incomplete test coverage. As a measure to reach Istio production quality in 0.3, this issue is opened to track the progress of providing sufficient test coverage for the feature in question.

This issue is initially assigned to the working group leads.

**Recommendations:**

- Come up with a test plan for how the feature should be tested. Identify and document (in this issue, or a separate document this issue will link to) test cases and whether each will be covered by an integration test (with some level of mocking and/or starting up selected components in test environment), or end to end test (aka system test, which brings up the whole Istio to exercise the feature; currently live in the istio/istio repo).
- If you expect the test plan is complex and controversial, consider having it formally [reviewed](http://goo.gl/pRuXqe).
- State an ETA in the issue, and assign this to a developer who will execute the test plan.
- Execute the test plan as the highest priority for 0.3.
- For any bug or defect identified by the new test cases, file a new issue and link it from this one.
Close this issue only when the test plan is completely executed, and all additional issues identified in step 3 are fixed.

If you see a risk of not fixing this issue by end of 0.3, please contact istio-production-quality@googlegroups.com as soon as possible. We will also periodically ping the issue for update.

**Comment by ozevren** [comment]
Andy,

Can you elaborate on how the deduction of "is identified as incomplete test coverage." is made? There is already an extensive slew of tests that has already been covering this feature. What is the exit criteria for this?

**Comment by hklai** [comment]
This came from https://docs.google.com/document/d/1-b9K5HfW3WRD7LLadlp4MsJtT5zq0b6pdzGt-0hBEtE/edit# and the worksheet (https://docs.google.com/document/d/1-b9K5HfW3WRD7LLadlp4MsJtT5zq0b6pdzGt-0hBEtE/edit#) after talking with @mandarjog and @douglas-reid.

AFAICT, there is currently no integration tests for Mixer. @douglas-reid and @mandarjog are looking into building some using the integration test framework. I will be meeting with them to discuss about that tomorrow to find out the plan.

**Comment by ozevren** [comment]
After offline discussion, I am closing this bug: The expression language itself is not a good target for integration tests: It neither has downstream component dependencies, nor it is restricted to a particular set of scenarios (thus requires particular tracking for integration testing purposes). Similar to other infrastructure pieces (such as gRpc server head), it is in the middle of any and all execution paths and will be tested as part of other integration tests.
