### ISSUE TITLE
Create an end-to-end perf test for Mixer.

### ISSUE THREAD

**Issue by geeknoid** [istio/old_mixer_repo#1472]
We want to be able to measure the real-world performance of Mixer under load. This work involves:

- Creating a real-world traffic flow to Mixer

- Creating a real-world configuration for Mixer including expected set of selectors and expression evaluation.

- Selecting a set of adapters representing real-world performance. Maybe we'll need a custom perf test adapter that can simulate the latency and memory consumption of typical adapters.

**Comment by ldemailly** [comment]
done
https://github.com/istio/istio/blob/master/tools/README.md
