### ISSUE TITLE
Add an expression cache

### ISSUE THREAD

**Issue by geeknoid** [istio/old_mixer_repo#1487]
We need to assess whether introducing a cache in front of the expression evaluation logic is desirable or not. If it is, we should add such a cache.

We need to determine whether the overhead of maintaining a cache is worth it. Expressions usually tend to be pretty short, so perhaps caching wouldn't bring us much.

**Comment by ozevren** [comment]
Resolving this as a duplicate of :https://github.com/istio/istio/issues/3572
While 3572 is newer, it is also in the new depot.
