### ISSUE TITLE
Introduce regex matching to Mixer expression language

### ISSUE THREAD

**Issue by geeknoid** [istio/old_mixer_repo#1493]
We should introduce support for regexes within the expression language which can help improve proxy cache efficiency.

See #1473 for the underlying support in the attribute package that will be needed for this to help with caching.

**Comment by geeknoid** [comment]
Is this done, can we close?

**Comment by ozevren** [comment]
"No".

I have an implementation available locally, but I am hesitant to submit it
yet:

   - It doesn't perform any attribute-bag-level marking of the regular
   expression.
   - CEL version of the 'matches' function is an instance level function
   (i.e. "pattern".matches("input")). The current type-checker does not allow
   instance-methods. As such, the only way to introduce it is as a regular
   function (i.e. matches("pattern", "input")). This means, we would also do a
   breaking change later to align with CEL.

**Comment by ozevren** [comment]
This implements the functionality, except for tracking the regex itself for cache keying purposes:
https://github.com/istio/istio/pull/1941
