### ISSUE TITLE
Add literal support (or converters from string) in the expression language for intrinsic types.

### ISSUE THREAD

**Issue by douglas-reid** [istio/old_mixer_repo#450]
From discussion in PR #412:

There are config types (email, ip addr, dns name, uri, etc.) that are not currently supported by the parsing bits of the expr language. We need to add the hand-parsing bits to derive the appropriate config.* types and enable downstream handling.

**Comment by geeknoid** [comment]
Is this still relevant?

**Comment by geeknoid** [comment]
I think the modern way to state this issue is that the expression language needs to have rich enough support to express literals of every supported attribute type, or at least needs to support functions that can take various inputs and return a value of the appropriate type.

**Comment by douglas-reid** [comment]
@geeknoid sure. and I think this is still relevant.

**Comment by ozevren** [comment]
This is done: https://github.com/istio/istio/pull/4156
