### ISSUE TITLE
Put in place procedure to extract reference docs and publish them to istio.github.io

### ISSUE THREAD

**Issue by geeknoid** [istio/old_mixer_repo#509]
We need to extract reference documentation for our config and push it into istio.github.io so that it shows up on www.istio.io.

We could have something that runs once a night, or once per commit to the repo. We need to figure out the right tools to extract the doc and what format to output, etc.

**Comment by geeknoid** [comment]
Also included here is extracting command-line options for our various commands.

The mixcol command we produce during a build can be used for this. You run this command and it'll output HTML describing the mixc and mixs commands by leveraging the Cobra library's ability to output nice docs for individual commands.

**Comment by ZackButcher** [comment]
To be clear: the deliverable for the alpha is a static set of documents. Post alpha we'll tackle automatically generating them at some regular internval. Does that match your understanding @geeknoid?

**Comment by geeknoid** [comment]
Yes, I think we can tackle automation separately.

So it's about producing the docs and wiring them appropriately in istio.io.

**Comment by douglas-reid** [comment]
What is the status here?  Are we able to close this (with the static docs we have now)?  Or do we need to wait until the final alpha cut?

**Comment by ZackButcher** [comment]
I checked in the last mixer docs today (the CLI stuff), but we still need to track the larger "make this happen automatically" task.

There's still one more round of generation that needs to happen pending some bug fixes in the doc gen tool.

**Comment by ayj** [comment]
@geeknoid, is this issue still relevant?

**Comment by geeknoid** [comment]
All done.
