### ISSUE TITLE
"Treat empty strings as nil in expr" potentially harmful

### ISSUE THREAD

**Issue by douglas-reid** [istio/old_mixer_repo#934]
https://github.com/istio/mixer/pull/825 is potentially harmful. It leads to surprising results for expressions that end in `| ""`. Instead of `""`, such an expression evals to `nil`.

Example:

`originUID: origin.uid | ""` -> `nil` (when `origin.uid` attribute is not present)

**Comment by douglas-reid** [comment]
Follow-up: Removing `| "` from these expressions in the config leads to unexpected behavior when the attributes aren't present:

Config:
```
...
  - kind: attributes
    params:
      input_expressions:
        sourceUID: source.uid
        targetUID: target.uid
        originUID: origin.uid
...
```

Result:
```
E0727 12:42:12.457917   88696 attrgenmgr.go:91] Could not evaluate input expressions for attribute generation.3 errors occurred:

* failed to construct value for label 'originUID': unresolved attribute origin.uid
* failed to construct value for label 'sourceUID': unresolved attribute source.uid
* failed to construct value for label 'targetUID': unresolved attribute target.uid
```

So, for now, we need to leave the `| ""` but know that that really means the value will be `nil` (and not `""`) when evaluated in the absence of the `*.uid` attribute.

**Comment by mandarjog** [comment]
Is `originUID: origin.uid | " "`  a workaround?
Note the single space instead of empty string.

**Comment by douglas-reid** [comment]
I don't think that we want to pass in `" "` instead of the empty string. That could lead to a bunch of code that has to `Trim` and the check `len > 0`, etc.

**Comment by ozevren** [comment]
The "|" operator now returns "" when LHS is an attribute and the attribute is not present.

**Comment by geeknoid** [comment]
Closing per Oz.
